
name: Schedule Job

on:
  schedule:
     - cron: "0 0 * * *"  #rat ke 12 baje perform kar dena automatic task

jobs:
   run-script:
     runs-on: ubuntu-latest

     steps:
       - name: Print Message
         run: echo "Schedule workflow executed"
     
